# Generated by Django 3.2.9 on 2021-11-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='company.company')),
                ('related_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_company', to='company.company')),
            ],
            options={
                'db_table': 'related_companies',
            },
        ),
    ]
